### ISSUE TITLE
Transparent bg preloader

### ISSUE THREAD

**Issue by shonnamartell** [tatthien/flat-preloader#1]
Do you have transparent background on any of your preloaders. I update the background of the page to black in css - however.. all the preloaders have white background.

**Comment by tatthien** [comment]
Hi @shonnamartell 

Currently, the flat-preloader doesn't have any transparent background. Sorry for that.

I'm thinking about a feature that users can use their own icons. However, I don't have much time to work on this plugin right now.

**Comment by tatthien** [comment]
Hi @shonnamartell 
Just release v1.5 that allows you to add a custom icon.

Cheer
